#####
# This is an example of docker compose file for Apillon pre-built solutions. You are encouraged to change it according to your needs.
#####

services:
  poa_db:
    image: mysql
    container_name: poa_db

    ## Enviroment variables can be set in .env files or from build environment
    ## Here is how you can use .env file (note: should be separate for each container)
    #    env_file:
    #      - .env.sql.deploy

    ## If you want to read variables from build environment comment out above section and uncomment below
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - '3306:3306'
    restart: always
    networks:
      - app-network

  poa_app:
    image: tadej/ps-poa:latest
    container_name: poa_app
    depends_on:
      - poa_db
    environment:
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      ADMIN_WALLET: ${ADMIN_WALLET}
      APILLON_KEY: ${APILLON_KEY}
      APILLON_SECRET: ${APILLON_SECRET}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_NAME_FROM: ${SMTP_NAME_FROM}
      SMTP_EMAIL_FROM: ${SMTP_EMAIL_FROM}

    ## Enviroment variables can be set in .env files or from build environment
    ## Here is how you can use .env file (note: should be separate for each container)
    #    env_file:
    #      - .env.production

    ports:
      - '80:3000'
    expose:
      - '80'
    restart: always
    networks:
      - app-network
networks:
  app-network:
    driver: bridge